stages:
  - build
  - deploy


build-check:
  stage: build
  rules:
    - if: $CI_COMMIT_BRANCH == "master"
  script:
    - earthly +build

package-bionic:
  stage: build
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - earthly +package
  artifacts:
    paths:
      - build/libpsinc*.deb

package-focal:
  stage: build
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - earthly --build-arg DISTRIBUTION=focal +package
  artifacts:
    paths:
      - build/libpsinc*.deb

package-windows:
  stage: build
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - earthly +windows
  artifacts:
    paths:
      - build/windows/*.7z

package-appimage:
  stage: build
  rules:
    - if: $CI_PIPELINE_SOURCE == "web"
      when: manual
  script:
    - earthly +appimage
  artifacts:
    paths:
      - build/*.AppImage

deploy-packages:
  stage: deploy
  rules:
    - if: $CI_COMMIT_TAG
  dependencies:
    - package-bionic
    - package-focal
    - package-windows
  script:
    - scp build/*.deb $DEPLOY_DOWNLOADS/libpsinc/ubuntu/
    - scp build/windows/*.7z $DEPLOY_DOWNLOADS/libpsinc/windows/

deploy-phi:
  stage: deploy
  rules:
    - if: $CI_COMMIT_TAG
  needs: [ package-bionic, package-focal ]
  script:
    - phi-deploy build/libpsinc0*~bionic_amd64.deb bionic oss
    - phi-deploy build/libpsinc0*~focal_amd64.deb focal oss
