#!/bin/bash

if [ $# -ne 1 ]; then
	echo "Usage: `basename $0` binary"
	exit 65
fi

if [ ! -e "$1" ]; then
	echo "Binary to strip must exist"
	exit 65
fi

count=`nm -a $1 | grep -c -w N`
if [[ $count > 0 ]]; then
	echo -n "Stripping binary..."
	objcopy --only-keep-debug $1 $1.dbg
	objcopy --strip-unneeded $1
	objcopy --add-gnu-debuglink=$1.dbg $1
	chmod -x $1.dbg
	echo "done"
else
	echo "Skipping since binary has already been stripped"
fi

exit 0
