set(CMAKE_SYSTEM_NAME Windows)
set(CMAKE_SYSTEM_PROCESSOR x86_64)
set(CMAKE_GENERATOR Ninja)
set(CMAKE_BUILD_TYPE Release)

set(CMAKE_C_COMPILER x86_64-w64-mingw32-gcc)
set(CMAKE_CXX_COMPILER x86_64-w64-mingw32-g++)
set(CMAKE_RC_COMPILER x86_64-w64-mingw32-windres)

set(CMAKE_FIND_ROOT_PATH /usr/x86_64-w64-mingw32)
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
# set(CMAKE_INSTALL_PREFIX /opt/qt6-win-x64)

set(QT_BUILD_EXAMPLES off)
set(QT_BUILD_TESTS off)
set(FEATURE_dbus off)
set(FEATURE_glib off)
# set(INPUT_opengl no)

# set(BUILD_qt3d off)
# set(BUILD_qtactiveqt off)
# set(BUILD_qtandroidextras off)
# set(BUILD_qtcanvas3d off)
# set(BUILD_qtconnectivity off)
# set(BUILD_qtdeclarative off)
# set(BUILD_qtdoc off)
# set(BUILD_qtdocgallery off)
# set(BUILD_qtfeedback off)
# set(BUILD_qtgraphicaleffects off)
# set(BUILD_qtmacextras off)
# set(BUILD_qtmultimedia off)
# set(BUILD_qtpim off)
# set(BUILD_qtpurchasing off)
# set(BUILD_qtqa off)
# set(BUILD_qtquickcontrols off)
# set(BUILD_qtquickcontrols2 off)
# set(BUILD_qtrepotools off)
# set(BUILD_qtscript off)
# set(BUILD_qtsensors off)
# set(BUILD_qtserialbus off)
# set(BUILD_qtsvg off)
# set(BUILD_qtsystems off)
# set(BUILD_qttools off)
# set(BUILD_qttranslations off)
# set(BUILD_qtwayland off)
# set(BUILD_qtwebchannel off)
# set(BUILD_qtwebengine off)
# set(BUILD_qtwebsockets off)
# set(BUILD_qtwebview off)
# set(BUILD_qtwinextras off)
# set(BUILD_qtx11extras off)
# set(BUILD_qtxmlpatterns off)
