name: CI

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

jobs:
  debs:
    name: Build debs
    runs-on: ubuntu-latest

    steps:
      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v1
        with:
          image: tonistiigi/binfmt:latest
          platforms: all

      - uses: earthly/actions/setup-earthly@v1
        with:
          version: v0.6.0

      - uses: actions/checkout@v2

      - name: Run build
        run: earthly +all

      - uses: actions/upload-artifact@v3
        with:
          path: build/**.deb


  appimage:
    name: Build AppImage
    runs-on: ubuntu-latest

    steps:
      - uses: earthly/actions/setup-earthly@v1
        with:
          version: v0.6.0

      - uses: actions/checkout@v2

      - name: Run build
        run: earthly +appimage

      - uses: actions/upload-artifact@v3
        with:
          path: build/**.AppImage


  windows:
    name: Cross-compile for windows
    runs-on: ubuntu-latest

    steps:
      - uses: earthly/actions/setup-earthly@v1
        with:
          version: v0.6.0

      - uses: actions/checkout@v2

      - name: Run build
        run: earthly +windows

      - uses: actions/upload-artifact@v3
        with:
          path: build/windows/**.7z


  release:
    name: Release
    runs-on: ubuntu-latest
    needs: [ debs, appimage, windows ]

    steps:
      - uses: actions/download-artifact@v3
        with:
          path: build/

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            build/**.deb
            build/**.AppImage
            build/**.7z
