name: gitlab-sync

on: 
  - push
  - delete
  - workflow_dispatch

jobs:
  sync:
    runs-on: ubuntu-latest
    name: Gitlab Sync
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: sync
      run: |
        git remote add target https://${{ secrets.TARGET_USERNAME }}:${{ secrets.TARGET_TOKEN }}@${{ secrets.TARGET_URL }}
        git push -f --all target
        git push -f --tags target
        
